export { ProtectedRoute, RoleRedirect } from './ProtectedRoute'
export { AsyncStateView } from './AsyncStateView'
export { ConnectionStatus } from './ConnectionStatus'
export {
  PortalHeader,
  HeaderStatusControl,
  HeaderNotificationsButton,
  HeaderProfileMenu,
  HeaderMenuButton,
  HamburgerIcon,
  HeaderGlyph,
  HeaderAdminSearch,
  profileMenuItems,
  customerNavItems,
  guestCustomerNavItems,
  guestProfileMenuItems,
  technicianNavItems,
  notificationsPath,
  type PortalRole,
  type HeaderMenuItem,
  type PortalHeaderProps,
} from './header'
export { MarketingRails } from './MarketingRails'
export { PremiumSponsorHero } from './PremiumSponsorHero'
export { SponsoredHeroBanner } from './SponsoredHeroBanner'
export { AppErrorBoundary, SectionErrorBoundary } from './AppErrorBoundary'
export { ProfilePhotoPicker } from './ProfilePhotoPicker'
export { ChatThread } from './ChatThread'
export { ConversationInbox } from './ConversationInbox'
export { NotificationsInbox } from './NotificationsInbox'
export { ReviewForm } from './ReviewForm'
export { MarkWorkCompleteDialog } from './jobs/MarkWorkCompleteDialog'
export { CustomerCompletionActions } from './jobs/CustomerCompletionActions'
export { AiAssistantPanel } from './AiAssistantPanel'
export { AiAssistantLauncher } from './AiAssistantLauncher'
export { AiGuestWelcome } from './AiGuestWelcome'
export {
  SkipLink,
  Dialog,
  DataTable,
  Th,
  ClickableRow,
  FormError,
  useReducedMotion,
  useFocusTrap,
  getFocusableElements,
} from './a11y'
export {
  CmsDocumentView,
  useCmsCopy,
  useContentBlocks,
  readContentCache,
  writeContentCache,
  clearContentCache,
  sanitizeContentHtml,
  type CmsDocumentViewProps,
  type CachedContent,
  type ContentChannel,
  type UseContentBlocksResult,
} from './content'
export { TrackingMap, LiveTrackingPanel, useTrackingPublisher, type MapPoint } from './tracking'
export {
  LocationPermissionHost,
  useLocationPermission,
  useOptionalLocationPermission,
  LocationSettingsCard,
  LocationEducationSheet,
  LocationFallbackBanner,
  LOCATION_COPY,
  isLocationPromptBlockedPath,
  reverseGeocodeCoords,
  distanceKm,
  formatDistanceKm,
  type LocationTrigger,
  type ReverseGeocodeResult,
} from './location'
export {
  AppDownloadReminderHost,
  useAppDownloadReminder,
  useOptionalAppDownloadReminder,
  APP_DOWNLOAD_COPY,
  isAppDownloadPromptBlockedPath,
  type AppDownloadTrigger,
  type AppDownloadRole,
} from './appDownload'
export {
  FixNowSplash,
  AppSplashGate,
  markColdSplashDone,
  COLD_SPLASH_SESSION_KEY,
  FIXNOW_MARK_SRC,
  checkBackendHealth,
  getBackendOrigin,
  prefetchEssentialContent,
  useNetworkStatus,
  isConclusiveOffline,
  isNetworkUsable,
  shouldShowSplashOfflineActions,
  useSplashController,
  resolveSplashTheme,
  type BackendHealthResult,
  type BackendHealthState,
  type NetworkStatus,
  type SplashController,
  type SplashControllerOptions,
  type SplashRole,
  type SplashThemeMode,
} from './splash'
export {
  UX_AUTH,
  UX_SUBSCRIPTION,
  UX_DEVELOPMENT,
  UX_SYSTEM,
  UX_MARKETPLACE,
  UX_PUBLIC_CATALOG,
  uxText,
  isPublicAudience,
  isDeveloperAudience,
  type UxAudience,
  type UxMessageKey,
  type UxMessageMeta,
} from './ux'
export {
  AuthShell,
  ForgotPasswordFlow,
  AuthAlert,
  AuthSubmitButton,
  AuthTextField,
  PasswordField,
  OtpInput,
  ResendCodeButton,
  RememberMeCheckbox,
  ContinueWithGoogleButton,
  AuthGateProvider,
  openAuthGate,
  useAuthGate,
  consumeResumeAction,
  getGuestSession,
  isGuestSession,
  enterGuestSession,
  clearGuestSession,
  setGuestPendingAction,
  getGuestPendingAction,
  clearGuestPendingAction,
  trackGuestEvent,
  isGuestBrowsePath,
  isGuestProtectedPath,
  SwitchRoleControl,
  RoleSelectPage,
  SessionEntryRedirect,
  ROLE_SELECT_PATH,
  marketplaceRolesOf,
  homePathForRole,
  resolvePostAuthDestination,
  resolveSessionResumeDestination,
  DevOtpNotice,
  useDevSettings,
  loadDevSettings,
  resetDevSettingsCache,
  useAuthSubmit,
  useResendCountdown,
  maskEmail,
  passwordValidationMessage,
  passwordsMatchMessage,
  getRememberedEmail,
  persistRememberedEmail,
  isCustomerOnboarded,
  setCustomerOnboarded,
  authFieldClassName,
  authActionButtonBase,
  authActionPrimaryClass,
  authActionSecondaryClass,
  authActionOutlineClass,
  authExpandPanelClass,
  authExpandPanelState,
  type GuestSession,
  type GuestPendingAction,
} from './auth'
