/**
 * Curated royalty-free photographic sources for FixNow visual upgrade.
 *
 * Licences: Unsplash License / Pexels License — free for commercial use.
 * Images are downloaded once and uploaded to Cloudinary (never hotlinked at runtime).
 */

export type VisualMediaKind =
  | 'categories'
  | 'heroes'
  | 'promotions'
  | 'advertisements'
  | 'campaigns'
  | 'knowledge'
  | 'academy'
  | 'technicians'
  | 'testimonials'
  | 'equipment'
  | 'tools'
  | 'safety'
  | 'emergency'
  | 'marketing'

export interface VisualMediaSource {
  /** Stable catalog key, e.g. categories.electrical */
  key: string
  /** Cloudinary folder under CLOUDINARY_FOLDER root */
  folder: string
  /** Stable public_id leaf (no folder prefix) */
  publicIdLeaf: string
  kind: VisualMediaKind
  alt: string
  tags: string[]
  /** Direct download URL (Unsplash/Pexels). Not used at runtime. */
  sourceUrl: string
  attribution: string
  /** Optional DB remaps after upload */
  applyTo?: {
    categorySlugs?: string[]
    promoTitleMatch?: RegExp
    sponsoredTitleMatch?: RegExp
    contentSlugs?: string[]
  }
}

const u = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`
const p = (id: number, w = 1600) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}`

export const VISUAL_MEDIA_SOURCES: VisualMediaSource[] = [
  // ── Categories (one photo → banner / square / cover via Cloudinary transforms) ──
  {
    key: 'categories.electrical',
    folder: 'categories',
    publicIdLeaf: 'electrical',
    kind: 'categories',
    alt: 'Electrician installing wiring in a residential panel',
    tags: ['category', 'electrical', 'technician'],
    sourceUrl: u('photo-1621905251189-08b45d6a269e'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['electrical'] },
  },
  {
    key: 'categories.generator',
    folder: 'categories',
    publicIdLeaf: 'generator',
    kind: 'categories',
    alt: 'Technician servicing a backup generator',
    tags: ['category', 'generator'],
    sourceUrl: u('photo-1473341304170-971dccb5ac1e'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['generator-repair'] },
  },
  {
    key: 'categories.emergency',
    folder: 'emergency',
    publicIdLeaf: 'emergency-repairs',
    kind: 'categories',
    alt: 'Emergency home repair response with professional tools',
    tags: ['category', 'emergency'],
    sourceUrl: u('photo-1504328345606-18bbc8c9d7d1'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['emergency-repairs'] },
  },
  {
    key: 'categories.plumbing',
    folder: 'categories',
    publicIdLeaf: 'plumbing',
    kind: 'categories',
    alt: 'Plumber repairing pipes under a sink',
    tags: ['category', 'plumbing'],
    sourceUrl: u('photo-1607472586893-edb57bdc0e39'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['plumbing'], sponsoredTitleMatch: /water conservation|leak early/i },
  },
  {
    key: 'categories.carpentry',
    folder: 'categories',
    publicIdLeaf: 'carpentry',
    kind: 'categories',
    alt: 'Carpenter cutting wood with professional tools',
    tags: ['category', 'carpentry'],
    sourceUrl: u('photo-1504148455328-c376907d081c'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['carpentry'] },
  },
  {
    key: 'categories.painting',
    folder: 'categories',
    publicIdLeaf: 'painting',
    kind: 'categories',
    alt: 'Painter applying fresh white paint to an interior wall',
    tags: ['category', 'painting'],
    sourceUrl: p(6474471),
    attribution: 'Pexels',
    applyTo: { categorySlugs: ['painting'] },
  },
  {
    key: 'categories.roofing',
    folder: 'categories',
    publicIdLeaf: 'roofing',
    kind: 'categories',
    alt: 'Roofing technicians working on a residential roof',
    tags: ['category', 'roofing'],
    sourceUrl: p(2219024),
    attribution: 'Pexels',
    applyTo: { categorySlugs: ['roofing'] },
  },
  {
    key: 'categories.cleaning',
    folder: 'categories',
    publicIdLeaf: 'cleaning',
    kind: 'categories',
    alt: 'Professional cleaner mopping a bright modern floor',
    tags: ['category', 'cleaning'],
    sourceUrl: u('photo-1581578731548-c64695cc6952'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['cleaning'] },
  },
  {
    key: 'categories.pest-control',
    folder: 'categories',
    publicIdLeaf: 'pest-control',
    kind: 'categories',
    alt: 'Pest control technician preparing treatment equipment',
    tags: ['category', 'pest-control'],
    sourceUrl: p(4239091),
    attribution: 'Pexels',
    applyTo: { categorySlugs: ['pest-control'] },
  },
  {
    key: 'categories.appliance-repair',
    folder: 'categories',
    publicIdLeaf: 'appliance-repair',
    kind: 'categories',
    alt: 'Technician repairing a home kitchen appliance',
    tags: ['category', 'appliance'],
    sourceUrl: u('photo-1556911220-bff31c812dba'),
    attribution: 'Unsplash',
    applyTo: {
      categorySlugs: ['appliance-repair', 'refrigerator-repair', 'washing-machine-repair', 'tv-electronics-repair'],
    },
  },
  {
    key: 'categories.hvac',
    folder: 'categories',
    publicIdLeaf: 'hvac',
    kind: 'categories',
    alt: 'HVAC technician servicing an air conditioning unit',
    tags: ['category', 'hvac'],
    sourceUrl: u('photo-1621905252507-b35492cc74b4'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['hvac'] },
  },
  {
    key: 'categories.solar',
    folder: 'categories',
    publicIdLeaf: 'solar',
    kind: 'categories',
    alt: 'Solar panels installed on a modern rooftop',
    tags: ['category', 'solar'],
    sourceUrl: u('photo-1509391366360-2e959784a276'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['solar'] },
  },
  {
    key: 'categories.internet-cctv',
    folder: 'categories',
    publicIdLeaf: 'internet-cctv',
    kind: 'categories',
    alt: 'Security camera and networking equipment installed outdoors',
    tags: ['category', 'cctv', 'internet'],
    sourceUrl: u('photo-1557597774-9d273605dfa9'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['internet-cctv', 'cctv-security', 'internet-networking'] },
  },
  {
    key: 'categories.locksmith',
    folder: 'categories',
    publicIdLeaf: 'locksmith',
    kind: 'categories',
    alt: 'Locksmith working on a residential door lock',
    tags: ['category', 'locksmith'],
    sourceUrl: u('photo-1558618666-fcd25c85cd64'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['locksmith'] },
  },
  {
    key: 'categories.landscaping',
    folder: 'categories',
    publicIdLeaf: 'landscaping',
    kind: 'categories',
    alt: 'Gardener maintaining a lush residential garden',
    tags: ['category', 'landscaping'],
    sourceUrl: u('photo-1416879595882-3373a0480b5b'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['landscaping'] },
  },
  {
    key: 'categories.moving',
    folder: 'categories',
    publicIdLeaf: 'moving',
    kind: 'categories',
    alt: 'Movers carrying boxes during a household relocation',
    tags: ['category', 'moving'],
    sourceUrl: u('photo-1600518464441-9154a4dea21b'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['moving'] },
  },
  {
    key: 'categories.handyman',
    folder: 'categories',
    publicIdLeaf: 'handyman',
    kind: 'categories',
    alt: 'Handyman using tools for a general home repair',
    tags: ['category', 'handyman'],
    sourceUrl: p(1249611),
    attribution: 'Pexels',
    applyTo: { categorySlugs: ['general-handyman'] },
  },
  {
    key: 'categories.welding',
    folder: 'categories',
    publicIdLeaf: 'welding',
    kind: 'categories',
    alt: 'Welder fabricating metal with protective gear',
    tags: ['category', 'welding'],
    sourceUrl: u('photo-1504328345606-18bbc8c9d7d1'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['welding-metal'] },
  },
  {
    key: 'categories.masonry',
    folder: 'categories',
    publicIdLeaf: 'masonry',
    kind: 'categories',
    alt: 'Bricklayer building a masonry wall',
    tags: ['category', 'masonry'],
    sourceUrl: u('photo-1504307651254-35680f356dfd'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['masonry'] },
  },
  {
    key: 'categories.tiling',
    folder: 'categories',
    publicIdLeaf: 'tiling',
    kind: 'categories',
    alt: 'Tile installer laying floor tiles',
    tags: ['category', 'tiling'],
    sourceUrl: p(5691622),
    attribution: 'Pexels',
    applyTo: { categorySlugs: ['tiling', 'flooring'] },
  },
  {
    key: 'categories.ceiling',
    folder: 'categories',
    publicIdLeaf: 'ceiling',
    kind: 'categories',
    alt: 'Ceiling installation with gypsum boards in progress',
    tags: ['category', 'ceiling'],
    sourceUrl: u('photo-1497366811353-6870744d04b2'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['ceiling-installation'] },
  },
  {
    key: 'categories.furniture',
    folder: 'categories',
    publicIdLeaf: 'furniture',
    kind: 'categories',
    alt: 'Furniture assembly with flat-pack parts and tools',
    tags: ['category', 'furniture'],
    sourceUrl: u('photo-1555041469-a586c61ea9bc'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['furniture-assembly'] },
  },
  {
    key: 'categories.glass',
    folder: 'categories',
    publicIdLeaf: 'glass',
    kind: 'categories',
    alt: 'Glass and aluminium window installation on a modern building',
    tags: ['category', 'glass'],
    sourceUrl: u('photo-1497366754035-f200968a6e72'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['glass-aluminium'] },
  },
  {
    key: 'categories.interior-design',
    folder: 'categories',
    publicIdLeaf: 'interior-design',
    kind: 'categories',
    alt: 'Styled modern interior living space after design work',
    tags: ['category', 'interior-design'],
    sourceUrl: u('photo-1616486338812-3dadae4b4ace'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['interior-design'] },
  },
  {
    key: 'categories.borehole',
    folder: 'categories',
    publicIdLeaf: 'borehole',
    kind: 'categories',
    alt: 'Water pump and tank system for borehole supply',
    tags: ['category', 'borehole', 'water'],
    sourceUrl: u('photo-1581092918056-0c4c3acd3789'),
    attribution: 'Unsplash',
    applyTo: { categorySlugs: ['borehole-water'] },
  },

  // ── Heroes ──
  {
    key: 'heroes.customer',
    folder: 'hero',
    publicIdLeaf: 'customer',
    kind: 'heroes',
    alt: 'Verified technician assisting a homeowner in a modern living space',
    tags: ['hero', 'customer', 'marketing'],
    sourceUrl: u('photo-1560518883-ce09059eeffa'),
    attribution: 'Unsplash',
  },
  {
    key: 'heroes.technician',
    folder: 'hero',
    publicIdLeaf: 'technician',
    kind: 'heroes',
    alt: 'Professional technician with tools ready for a service call',
    tags: ['hero', 'technician', 'marketing'],
    sourceUrl: u('photo-1621905252507-b35492cc74b4'),
    attribution: 'Unsplash',
  },

  // ── Promotions ──
  {
    key: 'promotions.first-booking',
    folder: 'offers',
    publicIdLeaf: 'first-booking',
    kind: 'promotions',
    alt: 'Happy homeowner welcoming a FixNow technician for a first booking',
    tags: ['promotion', 'offer', 'first-booking'],
    sourceUrl: u('photo-1556912173-46c336c7fd55'),
    attribution: 'Unsplash',
    applyTo: { promoTitleMatch: /first/i },
  },
  {
    key: 'promotions.weekend',
    folder: 'offers',
    publicIdLeaf: 'weekend',
    kind: 'promotions',
    alt: 'Weekend home maintenance with tools laid out ready for work',
    tags: ['promotion', 'weekend'],
    sourceUrl: p(1571460),
    attribution: 'Pexels',
    applyTo: { promoTitleMatch: /weekend/i },
  },
  {
    key: 'promotions.emergency',
    folder: 'emergency',
    publicIdLeaf: 'emergency-repair',
    kind: 'promotions',
    alt: 'Emergency electrician responding to an urgent repair call',
    tags: ['promotion', 'emergency'],
    sourceUrl: u('photo-1621905251189-08b45d6a269e'),
    attribution: 'Unsplash',
    applyTo: { promoTitleMatch: /emergency|electric/i },
  },
  {
    key: 'promotions.rainy-season',
    folder: 'offers',
    publicIdLeaf: 'rainy-season',
    kind: 'promotions',
    alt: 'Roof inspection during rainy season maintenance',
    tags: ['promotion', 'seasonal', 'roofing'],
    sourceUrl: u('photo-1504307651254-35680f356dfd'),
    attribution: 'Unsplash',
    applyTo: { promoTitleMatch: /rain|roof/i },
  },
  {
    key: 'promotions.safety-month',
    folder: 'safety',
    publicIdLeaf: 'safety-month',
    kind: 'promotions',
    alt: 'Home safety inspection with protective equipment',
    tags: ['promotion', 'safety'],
    sourceUrl: u('photo-1504328345606-18bbc8c9d7d1'),
    attribution: 'Unsplash',
    applyTo: { promoTitleMatch: /safety/i },
  },
  {
    key: 'promotions.referral',
    folder: 'offers',
    publicIdLeaf: 'referral',
    kind: 'promotions',
    alt: 'Two professionals shaking hands after a successful referral',
    tags: ['promotion', 'referral'],
    sourceUrl: u('photo-1521791136064-7986c2920216'),
    attribution: 'Unsplash',
    applyTo: { promoTitleMatch: /refer/i },
  },

  // ── Partner advertisements ──
  {
    key: 'advertisements.bank',
    folder: 'partners',
    publicIdLeaf: 'bank',
    kind: 'advertisements',
    alt: 'Modern bank and finance partnership imagery',
    tags: ['partner', 'bank', 'ad'],
    sourceUrl: u('photo-1563986768609-322da13575f3'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /bank/i },
  },
  {
    key: 'advertisements.insurance',
    folder: 'partners',
    publicIdLeaf: 'insurance',
    kind: 'advertisements',
    alt: 'Family home representing home insurance partnership',
    tags: ['partner', 'insurance', 'ad'],
    sourceUrl: u('photo-1560518883-ce09059eeffa'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /insurance/i },
  },
  {
    key: 'advertisements.building-materials',
    folder: 'partners',
    publicIdLeaf: 'building-materials',
    kind: 'advertisements',
    alt: 'Stacks of building materials at a construction supply yard',
    tags: ['partner', 'materials', 'ad'],
    sourceUrl: u('photo-1504307651254-35680f356dfd'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /material/i },
  },
  {
    key: 'advertisements.solar',
    folder: 'partners',
    publicIdLeaf: 'solar',
    kind: 'advertisements',
    alt: 'Solar energy partnership with rooftop panel installation',
    tags: ['partner', 'solar', 'ad'],
    sourceUrl: u('photo-1509391366360-2e959784a276'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /solar/i },
  },
  {
    key: 'advertisements.tools',
    folder: 'tools',
    publicIdLeaf: 'power-tools',
    kind: 'advertisements',
    alt: 'Professional power tools arranged for trade work',
    tags: ['partner', 'tools', 'ad'],
    sourceUrl: u('photo-1572981779307-38b8cabb2407'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /tool/i },
  },
  {
    key: 'advertisements.vehicle',
    folder: 'partners',
    publicIdLeaf: 'vehicle',
    kind: 'advertisements',
    alt: 'Service vehicle ready for technician field work',
    tags: ['partner', 'vehicle', 'ad'],
    sourceUrl: u('photo-1449965408869-eaa3f722e40d'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /vehicle|financ/i },
  },
  {
    key: 'advertisements.training',
    folder: 'academy',
    publicIdLeaf: 'pro-training',
    kind: 'advertisements',
    alt: 'Technicians in a professional training workshop',
    tags: ['partner', 'academy', 'training', 'ad'],
    sourceUrl: u('photo-1581092160562-40aa08e78837'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /train|academy/i },
  },
  {
    key: 'advertisements.telecom',
    folder: 'partners',
    publicIdLeaf: 'telecom',
    kind: 'advertisements',
    alt: 'Telecom and connectivity partnership imagery',
    tags: ['partner', 'telecom', 'ad'],
    sourceUrl: u('photo-1516321318423-f06f85e504b3'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /telecom|network/i },
  },

  // ── Campaigns / safety / education ──
  {
    key: 'campaigns.safety',
    folder: 'safety',
    publicIdLeaf: 'home-safety',
    kind: 'campaigns',
    alt: 'Home safety awareness campaign photography',
    tags: ['campaign', 'safety'],
    sourceUrl: u('photo-1558618666-fcd25c85cd64'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /home safety|safety month|safety walkthrough/i, contentSlugs: ['safety-tips'] },
  },
  {
    key: 'campaigns.choose-tech',
    folder: 'technicians',
    publicIdLeaf: 'choose-tech',
    kind: 'campaigns',
    alt: 'Trusted verified technician greeting a customer',
    tags: ['campaign', 'technician', 'trust'],
    sourceUrl: u('photo-1621905252507-b35492cc74b4'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /choose|trusted technician/i, contentSlugs: ['trust-verification'] },
  },
  {
    key: 'campaigns.seasonal',
    folder: 'marketing',
    publicIdLeaf: 'seasonal',
    kind: 'campaigns',
    alt: 'Seasonal home maintenance checklist in progress',
    tags: ['campaign', 'seasonal'],
    sourceUrl: u('photo-1484154218962-a197022b5858'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /fire safety|seasonal|dry season/i },
  },
  {
    key: 'campaigns.earnings',
    folder: 'marketing',
    publicIdLeaf: 'earnings',
    kind: 'campaigns',
    alt: 'Technician reviewing earnings on a mobile device',
    tags: ['campaign', 'earnings', 'technician'],
    sourceUrl: u('photo-1554224155-6726b3ff858f'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /earn|commission|business|energy sav/i },
  },
  {
    key: 'campaigns.verification',
    folder: 'technicians',
    publicIdLeaf: 'verification',
    kind: 'campaigns',
    alt: 'Technician completing identity verification documents',
    tags: ['campaign', 'verification'],
    sourceUrl: u('photo-1450101499163-c8848c66ca85'),
    attribution: 'Unsplash',
    applyTo: { sponsoredTitleMatch: /verif/i },
  },

  // ── Knowledge base covers ──
  {
    key: 'knowledge.electrical-safety',
    folder: 'knowledge',
    publicIdLeaf: 'electrical-safety',
    kind: 'knowledge',
    alt: 'Electrical safety cover — circuit breaker panel inspection',
    tags: ['knowledge', 'electrical', 'safety'],
    sourceUrl: u('photo-1621905251189-08b45d6a269e'),
    attribution: 'Unsplash',
    applyTo: { contentSlugs: ['electrical-safety'] },
  },
  {
    key: 'knowledge.water-leaks',
    folder: 'knowledge',
    publicIdLeaf: 'water-leaks',
    kind: 'knowledge',
    alt: 'Water leak prevention cover — plumbing inspection',
    tags: ['knowledge', 'plumbing'],
    sourceUrl: u('photo-1607472586893-edb57bdc0e39'),
    attribution: 'Unsplash',
    applyTo: { contentSlugs: ['water-leaks'] },
  },
  {
    key: 'knowledge.fire-prevention',
    folder: 'knowledge',
    publicIdLeaf: 'fire-prevention',
    kind: 'knowledge',
    alt: 'Fire prevention cover — smoke detector and safety check',
    tags: ['knowledge', 'fire', 'safety'],
    sourceUrl: u('photo-1558618666-fcd25c85cd64'),
    attribution: 'Unsplash',
    applyTo: { contentSlugs: ['fire-prevention'] },
  },
  {
    key: 'knowledge.generator-maintenance',
    folder: 'knowledge',
    publicIdLeaf: 'generator-maintenance',
    kind: 'knowledge',
    alt: 'Generator maintenance cover — backup power servicing',
    tags: ['knowledge', 'generator'],
    sourceUrl: u('photo-1473341304170-971dccb5ac1e'),
    attribution: 'Unsplash',
    applyTo: { contentSlugs: ['generator-maintenance'] },
  },
  {
    key: 'knowledge.roof-inspection',
    folder: 'knowledge',
    publicIdLeaf: 'roof-inspection',
    kind: 'knowledge',
    alt: 'Roof inspection cover — technician checking roof sheets',
    tags: ['knowledge', 'roofing'],
    sourceUrl: p(2219024),
    attribution: 'Pexels',
    applyTo: { contentSlugs: ['roof-inspection'] },
  },
  {
    key: 'knowledge.pest-prevention',
    folder: 'knowledge',
    publicIdLeaf: 'pest-prevention',
    kind: 'knowledge',
    alt: 'Pest prevention cover — home pest control preparation',
    tags: ['knowledge', 'pest'],
    sourceUrl: p(4239091),
    attribution: 'Pexels',
    applyTo: { contentSlugs: ['pest-prevention'] },
  },
  {
    key: 'knowledge.home-maintenance',
    folder: 'knowledge',
    publicIdLeaf: 'home-maintenance',
    kind: 'knowledge',
    alt: 'Home maintenance cover — tools for routine household care',
    tags: ['knowledge', 'maintenance'],
    sourceUrl: u('photo-1484154218962-a197022b5858'),
    attribution: 'Unsplash',
    applyTo: { contentSlugs: ['home-maintenance', 'about', 'help'] },
  },
  {
    key: 'knowledge.energy-saving',
    folder: 'knowledge',
    publicIdLeaf: 'energy-saving',
    kind: 'knowledge',
    alt: 'Energy saving cover — solar and efficient home power',
    tags: ['knowledge', 'energy'],
    sourceUrl: u('photo-1509391366360-2e959784a276'),
    attribution: 'Unsplash',
    applyTo: { contentSlugs: ['energy-saving'] },
  },
  {
    key: 'knowledge.emergency-response',
    folder: 'emergency',
    publicIdLeaf: 'emergency-response',
    kind: 'knowledge',
    alt: 'Emergency response cover — urgent home repair readiness',
    tags: ['knowledge', 'emergency'],
    sourceUrl: u('photo-1504328345606-18bbc8c9d7d1'),
    attribution: 'Unsplash',
    applyTo: { contentSlugs: ['emergency-response'] },
  },

  // ── Academy / technician portal ──
  {
    key: 'academy.workshop',
    folder: 'academy',
    publicIdLeaf: 'workshop',
    kind: 'academy',
    alt: 'FixNow Academy workshop with technicians in training',
    tags: ['academy', 'training'],
    sourceUrl: u('photo-1581092160562-40aa08e78837'),
    attribution: 'Unsplash',
  },
  {
    key: 'academy.certification',
    folder: 'academy',
    publicIdLeaf: 'certification',
    kind: 'academy',
    alt: 'Technician receiving professional certification',
    tags: ['academy', 'certification'],
    sourceUrl: p(267885),
    attribution: 'Pexels',
  },
  {
    key: 'academy.premium',
    folder: 'academy',
    publicIdLeaf: 'premium',
    kind: 'academy',
    alt: 'Premium technician workspace and professional setup',
    tags: ['academy', 'premium'],
    sourceUrl: u('photo-1497366216548-37526070297c'),
    attribution: 'Unsplash',
  },
  {
    key: 'technicians.portfolio',
    folder: 'technicians',
    publicIdLeaf: 'portfolio',
    kind: 'technicians',
    alt: 'Completed professional home repair work for a portfolio',
    tags: ['technician', 'portfolio', 'completed'],
    sourceUrl: u('photo-1484154218962-a197022b5858'),
    attribution: 'Unsplash',
  },
  {
    key: 'technicians.workspace',
    folder: 'technicians',
    publicIdLeaf: 'workspace',
    kind: 'technicians',
    alt: 'Organised technician workspace with tools and materials',
    tags: ['technician', 'workspace'],
    sourceUrl: u('photo-1572981779307-38b8cabb2407'),
    attribution: 'Unsplash',
  },
  {
    key: 'technicians.marketplace',
    folder: 'technicians',
    publicIdLeaf: 'marketplace',
    kind: 'technicians',
    alt: 'Technician marketplace — professionals ready for jobs',
    tags: ['technician', 'marketplace'],
    sourceUrl: u('photo-1521791136064-7986c2920216'),
    attribution: 'Unsplash',
  },
  {
    key: 'technicians.achievements',
    folder: 'technicians',
    publicIdLeaf: 'achievements',
    kind: 'technicians',
    alt: 'Achievement celebration for a high-performing technician',
    tags: ['technician', 'achievements'],
    sourceUrl: u('photo-1554224155-6726b3ff858f'),
    attribution: 'Unsplash',
  },
  {
    key: 'equipment.field',
    folder: 'equipment',
    publicIdLeaf: 'field-kit',
    kind: 'equipment',
    alt: 'Professional field equipment kit for home service calls',
    tags: ['equipment'],
    sourceUrl: u('photo-1581092918056-0c4c3acd3789'),
    attribution: 'Unsplash',
  },
  {
    key: 'tools.hand-tools',
    folder: 'tools',
    publicIdLeaf: 'hand-tools',
    kind: 'tools',
    alt: 'Organised hand tools for professional maintenance work',
    tags: ['tools'],
    sourceUrl: u('photo-1572981779307-38b8cabb2407'),
    attribution: 'Unsplash',
  },
  {
    key: 'testimonials.placeholder',
    folder: 'marketing',
    publicIdLeaf: 'customer-story',
    kind: 'testimonials',
    alt: 'Customer story — satisfied homeowner after a successful repair',
    tags: ['testimonial', 'marketing'],
    sourceUrl: u('photo-1556912173-46c336c7fd55'),
    attribution: 'Unsplash',
  },
]

/** Knowledge articles created/updated during visual seed (beyond legal/support defaults). */
export const KNOWLEDGE_ARTICLES = [
  {
    slug: 'electrical-safety',
    title: 'Electrical Safety at Home',
    excerpt: 'How to prevent shocks, overloaded circuits, and unsafe DIY wiring.',
    keywords: ['electrical', 'safety'],
    heroKey: 'knowledge.electrical-safety',
    bodyMarkdown: `# Electrical Safety at Home

Never ignore burning smells, warm sockets, or flickering lights. Hire a verified electrician for panel work, and keep payments in-app for accountability.`,
  },
  {
    slug: 'water-leaks',
    title: 'Spotting and Stopping Water Leaks',
    excerpt: 'Early signs of leaks and when to call a plumber.',
    keywords: ['plumbing', 'leaks'],
    heroKey: 'knowledge.water-leaks',
    bodyMarkdown: `# Spotting and Stopping Water Leaks

Check under sinks, around toilets, and along ceilings after heavy rain. Shut the main valve if flooding starts, then book a FixNow plumber.`,
  },
  {
    slug: 'fire-prevention',
    title: 'Fire Prevention Checklist',
    excerpt: 'Simple habits that reduce household fire risk.',
    keywords: ['fire', 'safety'],
    heroKey: 'knowledge.fire-prevention',
    bodyMarkdown: `# Fire Prevention Checklist

Test smoke detectors monthly, keep heaters clear of fabrics, and never leave cooking unattended. Book electrical inspections before the dry season peaks.`,
  },
  {
    slug: 'generator-maintenance',
    title: 'Generator Maintenance Basics',
    excerpt: 'Keep backup power reliable with routine servicing.',
    keywords: ['generator', 'maintenance'],
    heroKey: 'knowledge.generator-maintenance',
    bodyMarkdown: `# Generator Maintenance Basics

Change oil on schedule, keep fuel fresh, and run under load periodically. Use verified generator technicians for AVR and fuel-system repairs.`,
  },
  {
    slug: 'roof-inspection',
    title: 'Roof Inspection Before the Rains',
    excerpt: 'What to check on sheet roofs before rainy season.',
    keywords: ['roofing', 'inspection'],
    heroKey: 'knowledge.roof-inspection',
    bodyMarkdown: `# Roof Inspection Before the Rains

Look for loose sheets, rusted fasteners, and blocked gutters. Schedule a FixNow roofing check early to avoid emergency leaks.`,
  },
  {
    slug: 'pest-prevention',
    title: 'Pest Prevention for Homes',
    excerpt: 'Reduce termites, rodents, and cockroaches year-round.',
    keywords: ['pest', 'prevention'],
    heroKey: 'knowledge.pest-prevention',
    bodyMarkdown: `# Pest Prevention for Homes

Seal food, clear damp corners, and treat timber early. Book fumigation from verified pest-control technicians when activity appears.`,
  },
  {
    slug: 'home-maintenance',
    title: 'Monthly Home Maintenance Guide',
    excerpt: 'A practical checklist for Ugandan households.',
    keywords: ['maintenance', 'home'],
    heroKey: 'knowledge.home-maintenance',
    bodyMarkdown: `# Monthly Home Maintenance Guide

Walk through plumbing, electrics, locks, and outdoor drainage once a month. Small fixes booked early cost less than emergency call-outs.`,
  },
  {
    slug: 'energy-saving',
    title: 'Energy Saving Tips',
    excerpt: 'Cut power costs with smarter appliances and solar options.',
    keywords: ['energy', 'solar'],
    heroKey: 'knowledge.energy-saving',
    bodyMarkdown: `# Energy Saving Tips

Switch to LED lighting, unplug idle adapters, and consider a solar assessment for high daytime loads. FixNow connects you to verified solar installers.`,
  },
  {
    slug: 'emergency-response',
    title: 'Emergency Repair Response',
    excerpt: 'What to do when something fails after hours.',
    keywords: ['emergency'],
    heroKey: 'knowledge.emergency-response',
    bodyMarkdown: `# Emergency Repair Response

Secure the area, shut utilities if unsafe, and open an emergency booking in FixNow. Keep chats and payments in-app so help stays trackable.`,
  },
]
