/**
 * Cloudinary visual catalog helpers.
 * `cloudinary-catalog.json` is generated by `backend/scripts/seed-visual-assets.ts`.
 */

import catalogJson from './cloudinary-catalog.json'

export type CloudinaryCatalogAsset = {
  key: string
  publicId: string
  url: string
  folder: string
  alt: string
  tags: string[]
  width?: number
  height?: number
  bytes?: number
  format?: string
  attribution: string
  kind: string
}

export type CloudinaryCatalogFile = {
  generatedAt?: string | null
  cloudName?: string | null
  folderRoot?: string
  count?: number
  assets: Record<string, CloudinaryCatalogAsset>
}

const catalog = catalogJson as CloudinaryCatalogFile

export function loadCloudinaryCatalog(): CloudinaryCatalogFile {
  return catalog?.assets ? catalog : { assets: {} }
}

export function cloudinaryCatalogUrl(key: string): string | undefined {
  const url = loadCloudinaryCatalog().assets[key]?.url
  return url ? String(url) : undefined
}

export function cloudinaryCatalogAlt(key: string): string | undefined {
  const alt = loadCloudinaryCatalog().assets[key]?.alt
  return alt ? String(alt) : undefined
}

export function cloudinaryCatalogAsset(key: string): CloudinaryCatalogAsset | undefined {
  return loadCloudinaryCatalog().assets[key]
}
