/**
 * Error codes + categories for structured diagnostics (no operator config).
 */

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  TIMEOUT: 'TIMEOUT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DEPENDENCY_FAILED: 'DEPENDENCY_FAILED',
  CIRCUIT_OPEN: 'CIRCUIT_OPEN',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Coarse buckets for metrics / dashboards — independent of HTTP status. */
export const ERROR_CATEGORIES = {
  VALIDATION: 'validation',
  AUTH: 'auth',
  AUTHORIZATION: 'authorization',
  NOT_FOUND: 'not_found',
  CONFLICT: 'conflict',
  RATE_LIMIT: 'rate_limit',
  CLIENT: 'client',
  DEPENDENCY: 'dependency',
  TIMEOUT: 'timeout',
  INTERNAL: 'internal',
} as const;

export type ErrorCategory = (typeof ERROR_CATEGORIES)[keyof typeof ERROR_CATEGORIES];

const CODE_CATEGORY: Partial<Record<ErrorCode, ErrorCategory>> = {
  [ERROR_CODES.VALIDATION_ERROR]: ERROR_CATEGORIES.VALIDATION,
  [ERROR_CODES.BAD_REQUEST]: ERROR_CATEGORIES.CLIENT,
  [ERROR_CODES.UNAUTHORIZED]: ERROR_CATEGORIES.AUTH,
  [ERROR_CODES.FORBIDDEN]: ERROR_CATEGORIES.AUTHORIZATION,
  [ERROR_CODES.ACCOUNT_LOCKED]: ERROR_CATEGORIES.AUTH,
  [ERROR_CODES.ACCOUNT_SUSPENDED]: ERROR_CATEGORIES.AUTH,
  [ERROR_CODES.ACCOUNT_PENDING]: ERROR_CATEGORIES.AUTH,
  [ERROR_CODES.INVALID_OTP]: ERROR_CATEGORIES.AUTH,
  [ERROR_CODES.OTP_EXPIRED]: ERROR_CATEGORIES.AUTH,
  [ERROR_CODES.NOT_FOUND]: ERROR_CATEGORIES.NOT_FOUND,
  [ERROR_CODES.CONFLICT]: ERROR_CATEGORIES.CONFLICT,
  [ERROR_CODES.IDEMPOTENCY_CONFLICT]: ERROR_CATEGORIES.CONFLICT,
  [ERROR_CODES.RATE_LIMITED]: ERROR_CATEGORIES.RATE_LIMIT,
  [ERROR_CODES.DATABASE_UNAVAILABLE]: ERROR_CATEGORIES.DEPENDENCY,
  [ERROR_CODES.TIMEOUT]: ERROR_CATEGORIES.TIMEOUT,
  [ERROR_CODES.PAYLOAD_TOO_LARGE]: ERROR_CATEGORIES.CLIENT,
  [ERROR_CODES.UPLOAD_FAILED]: ERROR_CATEGORIES.CLIENT,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: ERROR_CATEGORIES.DEPENDENCY,
  [ERROR_CODES.DEPENDENCY_FAILED]: ERROR_CATEGORIES.DEPENDENCY,
  [ERROR_CODES.CIRCUIT_OPEN]: ERROR_CATEGORIES.DEPENDENCY,
  [ERROR_CODES.NETWORK_ERROR]: ERROR_CATEGORIES.DEPENDENCY,
  [ERROR_CODES.NOT_IMPLEMENTED]: ERROR_CATEGORIES.INTERNAL,
  [ERROR_CODES.INTERNAL_ERROR]: ERROR_CATEGORIES.INTERNAL,
};

export function categorizeError(code: string, statusCode?: number): ErrorCategory {
  const mapped = CODE_CATEGORY[code as ErrorCode];
  if (mapped) return mapped;
  if (statusCode === 401) return ERROR_CATEGORIES.AUTH;
  if (statusCode === 403) return ERROR_CATEGORIES.AUTHORIZATION;
  if (statusCode === 404) return ERROR_CATEGORIES.NOT_FOUND;
  if (statusCode === 409) return ERROR_CATEGORIES.CONFLICT;
  if (statusCode === 422 || statusCode === 400) return ERROR_CATEGORIES.VALIDATION;
  if (statusCode === 429) return ERROR_CATEGORIES.RATE_LIMIT;
  if (statusCode === 408 || statusCode === 504) return ERROR_CATEGORIES.TIMEOUT;
  if (statusCode === 502 || statusCode === 503) return ERROR_CATEGORIES.DEPENDENCY;
  if (statusCode && statusCode >= 500) return ERROR_CATEGORIES.INTERNAL;
  if (statusCode && statusCode >= 400) return ERROR_CATEGORIES.CLIENT;
  return ERROR_CATEGORIES.INTERNAL;
}
