/**
 * Push notification event catalog + category mapping.
 * Categories map to NotificationPreference.categories keys.
 */

export const PUSH_CATEGORIES = {
  AUTH: 'auth',
  MARKETPLACE: 'marketplace',
  MESSAGING: 'messaging',
  ADMIN: 'admin',
} as const;

export type PushCategory = (typeof PUSH_CATEGORIES)[keyof typeof PUSH_CATEGORIES];

export const PUSH_EVENTS = {
  // Auth
  AUTH_WELCOME: 'auth.welcome',
  AUTH_PASSWORD_RESET: 'auth.password_reset',
  AUTH_ACCOUNT_LOCKED: 'auth.account_locked',
  AUTH_ACCOUNT_UNLOCKED: 'auth.account_unlocked',

  // Marketplace
  JOB_PUBLISHED: 'job.published',
  TECHNICIAN_APPLIED: 'application.received',
  TECHNICIAN_ASSIGNED: 'application.accepted',
  TECHNICIAN_EN_ROUTE: 'job.technician_en_route',
  JOB_STARTED: 'job.in_progress',
  JOB_COMPLETED: 'job.completed',
  JOB_CANCELLED: 'job.cancelled',
  JOB_STATUS: 'job.status',

  // Messaging
  MESSAGE_NEW: 'message.new',
  MESSAGE_MENTION: 'message.mention',
  MESSAGE_ATTACHMENT: 'message.attachment',

  // Admin / system
  REVIEW_RECEIVED: 'review.received',
  REVIEW_EDITED: 'review.edited',
  BADGE_EARNED: 'badge.earned',
  PAYMENT_SUCCESSFUL: 'payment.successful',
  PAYMENT_FAILED: 'payment.failed',
  ESCROW_FUNDED: 'escrow.funded',
  ESCROW_RELEASED: 'escrow.released',
  REFUND_PROCESSED: 'refund.processed',
  REFUND_REQUESTED: 'refund.requested',
  PAYOUT_COMPLETED: 'payout.completed',
  USER_REGISTERED: 'admin.user_registered',
  TECHNICIAN_LOCKED: 'technician.locked',
  TECHNICIAN_UNLOCKED: 'technician.unlocked',
  MARKETPLACE_ALERT: 'admin.marketplace_alert',
  SYSTEM_ANNOUNCEMENT: 'admin.announcement',
} as const;

export type PushEventType = (typeof PUSH_EVENTS)[keyof typeof PUSH_EVENTS] | string;

const EVENT_CATEGORY: Record<string, PushCategory> = {
  [PUSH_EVENTS.AUTH_WELCOME]: PUSH_CATEGORIES.AUTH,
  [PUSH_EVENTS.AUTH_PASSWORD_RESET]: PUSH_CATEGORIES.AUTH,
  [PUSH_EVENTS.AUTH_ACCOUNT_LOCKED]: PUSH_CATEGORIES.AUTH,
  [PUSH_EVENTS.AUTH_ACCOUNT_UNLOCKED]: PUSH_CATEGORIES.AUTH,
  [PUSH_EVENTS.JOB_PUBLISHED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.TECHNICIAN_APPLIED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.TECHNICIAN_ASSIGNED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.TECHNICIAN_EN_ROUTE]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.JOB_STARTED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.JOB_COMPLETED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.JOB_CANCELLED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.JOB_STATUS]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.MESSAGE_NEW]: PUSH_CATEGORIES.MESSAGING,
  [PUSH_EVENTS.MESSAGE_MENTION]: PUSH_CATEGORIES.MESSAGING,
  [PUSH_EVENTS.MESSAGE_ATTACHMENT]: PUSH_CATEGORIES.MESSAGING,
  [PUSH_EVENTS.USER_REGISTERED]: PUSH_CATEGORIES.ADMIN,
  [PUSH_EVENTS.REVIEW_RECEIVED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.REVIEW_EDITED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.BADGE_EARNED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.PAYMENT_SUCCESSFUL]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.PAYMENT_FAILED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.ESCROW_FUNDED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.ESCROW_RELEASED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.REFUND_PROCESSED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.REFUND_REQUESTED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.PAYOUT_COMPLETED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.TECHNICIAN_LOCKED]: PUSH_CATEGORIES.ADMIN,
  [PUSH_EVENTS.TECHNICIAN_UNLOCKED]: PUSH_CATEGORIES.MARKETPLACE,
  [PUSH_EVENTS.MARKETPLACE_ALERT]: PUSH_CATEGORIES.ADMIN,
  [PUSH_EVENTS.SYSTEM_ANNOUNCEMENT]: PUSH_CATEGORIES.ADMIN,
};

export function categoryForEvent(eventType: string): PushCategory {
  if (EVENT_CATEGORY[eventType]) return EVENT_CATEGORY[eventType];
  if (eventType.startsWith('auth.')) return PUSH_CATEGORIES.AUTH;
  if (eventType.startsWith('message.')) return PUSH_CATEGORIES.MESSAGING;
  if (eventType.startsWith('admin.')) return PUSH_CATEGORIES.ADMIN;
  return PUSH_CATEGORIES.MARKETPLACE;
}
